#!/bin/sh

userresources=$HOME/.Xresources
usermodmap=$HOME/.Xmodmap
sysresources=/etc/X11/xinit/.Xresources
sysmodmap=/etc/X11/xinit/.Xmodmap

# merge in defaults and keymaps

if [ -f $sysresources ]; then







    xrdb -merge $sysresources

fi

if [ -f $sysmodmap ]; then
    xmodmap $sysmodmap
fi

if [ -f "$userresources" ]; then







    xrdb -merge "$userresources"

fi

if [ -f "$usermodmap" ]; then
    xmodmap "$usermodmap"
fi

# start some nice programs

if [ -d /etc/X11/xinit/xinitrc.d ] ; then
 for f in /etc/X11/xinit/xinitrc.d/?*.sh ; do
  [ -x "$f" ] && . "$f"
 done
 unset f
fi

#
# Start sxhkd with the fastest shell. Since it is our hotkey daemon, it needs
# to be quick.
#
export SXHKD_SHELL='/usr/bin/sh'

#
# Switch the cursor from X11's default cross to the more familiar arrow.
#
xsetroot -cursor_name left_ptr

feh --bg-scale --no-fehbg --randomize /usr/local/share/backgrounds/* &
exec bspwm
