#=============================================================================
# dark_powered.toml --- dark powered configuration example for SpaceVim
# Copyright (c) 2016-2017 Wang Shidong & Contributors
# Author: Wang Shidong < wsdjeg at 163.com >
# URL: https://spacevim.org
# License: GPLv3
#=============================================================================

[options]
  #
  # Load custom vim configurations.
  #
  bootstrap_before = "bootstrap#before"

  #
  # This color scheme is provided by the 'chriskempson/base16-vim' plugin.
  #
  colorscheme = "base16-gruvbox-dark-hard"
  colorscheme_bg = "dark"

  #
  # Use the Hack font patched by the Nerd Fonts project.
  #
  #   https://sourcefoundry.org/hack/
  #   https://www.nerdfonts.com/
  #
  # This only applies when opening vim or neovim in a GUI application. When
  # opening from a terminal, this configuration lives with the terminal.
  #
  guifont = "Hack Nerd Font Mono:h16"

  #
  # Customize the display of the status line.
  #
  statusline_right_sections = [
    "fileformat",
    "percentage",
    "cursorpos"
  ]

  #
  # Do not remap the "s", "q", and "," keys for SpaceVim. It's very valuable
  # to use these keys for other purposes.
  #
  vimcompatible = true

  #
  # Do not show the file tree on startup to speed things up.
  #
  enable_vimfiler_welcome = false

  #
  # Turn off snippets to speed up load time. I don't find them useful.
  #
  snippet_engine = ""

  #
  # Disable plugins I do not use that SpaceVim adds by default.
  #
  disabled_plugins = [
    "CompleteParameter.vim",
    "neco-syntax",
    "neoinclude.vim",
    "neosnippet-snippets",
    "vim-snippets",
  ]

  #
  # Use coc.nvim to power autocompletion.
  #
  #  https://github.com/neoclide/coc.nvim
  #
  autocomplete_method = "coc"

  #
  # Load custom vim configurations.
  #
  bootstrap_after = "bootstrap#after"

[[layers]]
  name = "autocomplete"

  #
  # When the Return/Enter key is pressed, completes with the current selection.
  #
  auto_completion_return_key_behavior = "complete"

  #
  # When the TAB key is pressed, cycle candidates, expand snippets, and jump
  # parameters.
  #
  auto_completion_tab_key_behavior = "smart"

[[layers]]
  #
  # We will try to use and improve coc.nvim for this.
  #
  name = "checkers"
  enable = false

[[layers]]
  #
  # Enable this again if neoformat is needed.
  #
  name = "format"
  enable = false

[[layers]]
  #
  # Enable the fuzzy finder.
  #
  name = "fzf"

[[layers]]
  #
  # Disable access to the shell in vim. We will use tmux panes for this.
  #
  name = "shell"
  enable = false

[[layers]]
  #
  # Enable seamless navigation between vim and tmux panes.
  #
  name = "tmux"

[[custom_plugins]]
  #
  # This plugin makes base16 themes available to Vim. Base16 is an architecture
  # for building themes that provide consistent colors for syntax highlighting.
  #
  name = "chriskempson/base16-vim"

[[custom_plugins]]
  #
  # This plugin saves vim session automatically.
  #
  name = "tpope/vim-obsession"

[[custom_plugins]]
  #
  # This plugin highlights the yanked region for some time.
  #
  name = "machakann/vim-highlightedyank"

[[custom_plugins]]
  #
  # This plugin extends vim's % key to match language-specific words.
  #
  name = "andymass/vim-matchup"

[[custom_plugins]]
  #
  # Syntax support for TOML.
  #
  name = "cespare/vim-toml"

[[custom_plugins]]
  #
  # Syntax support for YAML.
  #
  name = "stephpy/vim-yaml"

[[custom_plugins]]
  #
  # Syntax support for Rust.
  #
  name = "rust-lang/rust.vim"

[[custom_plugins]]
  #
  # Syntax support for Fish.
  #
  name = "dag/vim-fish"

[[custom_plugins]]
  #
  # Syntax support for Markdown.
  #
  name = "plasticboy/vim-markdown"
